### ISSUE TITLE
Impossible to add an element

### ISSUE THREAD

**Issue by laurendang95** [FriendsOfVictoire/WidgetListingBundle#24]
When I created a list, I just can't add a new element in it. The button "Add a new element" didn't react. 

<img width="1280" alt="capture d ecran 2017-09-27 a 14 10 02" src="https://user-images.githubusercontent.com/32325557/30912635-acffb4ca-a38d-11e7-94f5-ec893125563f.png">

**Comment by alexisLefebvre** [comment]
This issue can be closed since #31 has been merged.
